language: ruby

rvm:
  - 2.0.0

env:
  - DB=postgresql SECRET_TOKEN=3457f9d6b2b35dd58ab98630210674a5a0277d05c5f9dfe8d3375283f74e65dc03367fb3e32594c3bbf131c8261a553a19c34ee57fc5363f1f78853745d4bdd6

before_script:
  - curl -Lo config/database.yml http://git.io/YLiX3g
  - bundle --quiet
  - bundle exec rake db:setup

script:
  - RAILS_ENV=test bundle exec rspec spec
